## Machine learning

Classificacao Binaria E Lineares<br>

Regresao Logistica<br>
SVM<br>
Bayes: unico que nao serve em problemas multiclasse

Classificacao Binaria E Nao Lineares<br>
Arvores<br>
Redes Neurais

Supervisionado: Deterministico e Estocastico<br>
Nao Supervisionado: Procura, Otimizacao(formula um problema em que precisa maximizar o resultado)

## Enasamble

metodo Conjunto: no qual usase uma colecao de hipoteses, que escolhe melhor opcao para classificador

como tenho muitos modelos, verrificando varias hipoteses, aumento o bias, diminuo a variancia

Bagging: amostra com reposicao(mais bias) <br>
out of bag: amostras restantes usadas para estimativas<br>

Pasting: amostra sem reposicao() <br>

metodolodia de votacao<br>
heading voating: voto majoritario ou media<br>
soft voting: requer estimadores com probabilidade bem calibrada


AdBoosting: treina o primeiro modelo, ele tenta corrigir os erros um do outro<br>
treinamento sequencial, calcula-se o argumento maximo de K

In [ ]:
gra

## Reducao Dimensionalidade

In [ ]:
as empresas, replicacoes

# Bias e Variancia

vies: o quanto em media o modelo que construiomos esta distante do resultado medio <br>
vairianca: quanto desvia da media das predicoes dos modelos

vies e variance: sao inversamente porpocional

bias: quando for grande vamos errar muito<br>
variancia: vaira de modelo em modelo

Modelos de alta complexidade: Bias pequeno e alta variancia<br>
Modelos de baixa complexidade: pequena variancia alto bias

Trade-off: conflito de escolha

# Feature Engineering

Valores faltantes<br>
Outiliers<br>
Novas variaveis<br>
Deleção de variaveis<br>
Classes desbalanceadas<br>
Normalizacao e Padronizacao<br>
Codificacao


### Escalonamento de Atributos

MinMax: seleciona cada uma das features e calcula o minimo e maximo de cada uma<br>
<b>Recomendado quando temos certeza que na amostra temos o minimo e maximo para cada uma das features

In [ ]:
peso =[69,71.1,79]
x=[]
for i in range(len(peso)):
    x.append((peso[i] - min(peso))/(max(peso) -min(peso)))
x

[0.0, 0.20999999999999944, 1.0]

Normalizacao

In [ ]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
# deixa na escala entre 0 e 1 
# normalizacao, utilizada quando os algoritimos nao seguem nenhuma distribuicao, util no knn e redes neurais
# sensivel a outliers 

v = np.array(peso)
# Normalizando os dados
mx = MinMaxScaler().fit(v.reshape(-1, 1)) # cria objeto
mx.transform(v.reshape(-1, 1))


array([[0.  ],
       [0.21],
       [1.  ]])

Padronizacao

In [ ]:
import numpy as np 
# media 0 e dvp 1 
# util quando segue um distribuicao, nao afeta os valores 

peso =[69,71.1,79]
dvp = np.std(peso)
med = np.mean(peso)
z=[]
for i in range(len(peso)):
    z.append((peso[i] - med)/dvp)
z

[-0.9368311265351539, -0.4490595482565211, 1.3858906747916748]

In [ ]:
st = StandardScaler().fit(v.reshape(-1,1))
st.transform(v.reshape(-1,1))

array([[-0.93683113],
       [-0.44905955],
       [ 1.38589067]])


# Validacao cruzada

Kfold

Corremos o risco de nao pegar os melhores registros<br>
pega o conjjunto de treino e separa em K pedacos, pega o k restante e treina e depois o k final<br><br>
kfold: numero de quebras na base de dados, ex: 4(3 para treinamento, 1 teste) <br><br>
Sem mecher no conjunto de teste

In [53]:
from sklearn.model_selection import cross_val_score,KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris

iris = load_iris()
X=iris.data
y=iris.target

kf = KFold(n_splits=20,shuffle=True)# shuffle e o embaralhamento
knn = KNeighborsClassifier(n_neighbors=3)
scores = cross_val_score(knn,X,y,cv=kf,scoring="accuracy")
# descobrindo a acuracia media q meu modelo deve ter 
np.mean(scores),scores

(0.9589285714285716,
 array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.875     , 0.875     , 1.        ,
        1.        , 0.85714286, 1.        , 1.        , 0.85714286,
        1.        , 1.        , 0.85714286, 0.85714286, 1.        ]))

Monte carlo cross val

In [74]:
# repete um processo varias vezes
# menor variancia, bias maior
from sklearn.model_selection import ShuffleSplit,KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris

iris = load_iris()
X=iris.data
y=iris.target

kf = KFold(n_splits=20,shuffle=True)# shuffle e o embaralhamento, serve para dividir
knn = KNeighborsClassifier(n_neighbors=3)
ss = ShuffleSplit(n_splits=5,test_size=0.25)


Otimizando algoritimos com gridSearch

In [82]:
from sklearn.model_selection import GridSearchCV

# busca em grade, valiacao cruzada 
parametros = {'n_neighbors':[1,2,3,4,5,6,7,8,9,10,11],
               'metric':['minkowski','euclidian']
}

gd = GridSearchCV(estimator=KNeighborsClassifier(),param_grid=parametros);
gd.fit(X,y);


c:\Users\Familia\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
55 fits failed out of a total of 110.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
55 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Familia\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Familia\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py", line 200, in fit
    return self._fit(X, y)
  File "c:\Users\Familia\anaconda3\lib\site-packages\sklearn\neighbors\_base.py", line 446, in _fit
    self._check_algorithm_metric()
  File "c:\Users\Familia\anaconda3

In [84]:
np.mean(scores),gd.best_params_,gd.best_score_

(0.9589285714285716,
 {'metric': 'minkowski', 'n_neighbors': 6},
 0.9800000000000001)

# Avaliacao

Classificacao

na classe 1, ele indentifica 100% das flores que pertencem a classe e ele esta acertando 50% <br>
50% precisao e 100% recall<br>
f1: media harmonica entre precisao

f-beta score: Media ponderada, que mede a relacao da precisao e recall,recall tem um peso maior que a precisão.<br>
isso é util em problemas onde queremos ter certeza que o nosso classificador é bom em identificar a classe positiva, mesmo que pra isso ele acabe gerando mais falsos positivos.

Log-loss: e a probabiliodade dos rotulos de fato acontecerem

log-loss: minimiza a entropia cruzada, quanto menor a perda melhor, nescessita de probabilidade para todas as classes
<br>
output de probabilidade<br>

Tomando os cuidados acima, nas situações em que a probabilidade de um exemplo pertencer a uma classe for mais importante do que classificá-lo diretamente, esta função é preferível a usar simplesmente a precisão geral.

## Escalonamento de Atributos

MinMax: seleciona cada uma das features e calcula o minimo e maximo de cada uma<br>
<b>Recomendado quando temos certeza que na amostra temos o minimo e maximo para cada uma das features

In [ ]:
peso =[69,71.1,79]
x=[]
for i in range(len(peso)):
    x.append((peso[i] - min(peso))/(max(peso) -min(peso)))
x

[0.0, 0.20999999999999944, 1.0]

Normalizacao

In [ ]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
# deixa na escala entre 0 e 1 
# normalizacao, utilizada quando os algoritimos nao seguem nenhuma distribuicao, util no knn e redes neurais
# sensivel a outliers 

v = np.array(peso)
# Normalizando os dados
mx = MinMaxScaler().fit(v.reshape(-1, 1)) # cria objeto
mx.transform(v.reshape(-1, 1))


array([[0.  ],
       [0.21],
       [1.  ]])

Padronizacao

In [ ]:
import numpy as np 
# media 0 e dvp 1 
# util quando segue um distribuicao, nao afeta os valores 

peso =[69,71.1,79]
dvp = np.std(peso)
med = np.mean(peso)
z=[]
for i in range(len(peso)):
    z.append((peso[i] - med)/dvp)
z

[-0.9368311265351539, -0.4490595482565211, 1.3858906747916748]

In [ ]:
st = StandardScaler().fit(v.reshape(-1,1))
st.transform(v.reshape(-1,1))

array([[-0.93683113],
       [-0.44905955],
       [ 1.38589067]])

# Multiclasse

Ovr: determina por meio de um plano tracado em qualclasse esta seu modelo, verrifica se de fato esta na classe 1-All<br>

Ovo:um contr um, ele compara classe com classe Any: quando modelo nao e escalavel

# Gradiente

Faz a calibracao dos valores ate o resultado ideal, muito longe ele vaminha mais, mais perto ele vai de pouco em pouco<br>


funcao de custo: Determina a diferenca entre o predito e o valor real, ou seja o erro quadratico


# Tecnicas de Regularizacao

utilizado nas regressoes<br>
Reduzir parametros<br>


# Dados faltantes

excluir colunas ou instancias: quando amostra e muito grande<br>
imputacao univariada: estatisticas simples. as vezes nao e representativa e destruimos as correlacao<br>
classe: moda, idade: media, horas: mediana, salario mediana<br>



Mcar(missing completely at random): ausencia de forma aletoria sem relacao com outras informacoes<br>
Mar(missing at random): ausencia pode ser explicada por outras questoes(nao querer dizer genero, por n coisas, n variaveis) <br>
MnR(missing is not random): relacao com ela mesma(nivel de ingles, nao conseguimos prencher )

MICE: jogamos um palpite, ele tenta melhorar, com iteracoes apartir de outras colunas 

In [100]:
# maneira simples univariada
import numpy as np 
from sklearn.impute import SimpleImputer
arr = np.array([10,np.nan,5,10,33])
arr = arr.reshape(-1, 1)
imp = SimpleImputer(missing_values=np.nan,strategy='mean')
imp.fit(arr)
imp.transform(arr)

array([[10. ],
       [14.5],
       [ 5. ],
       [10. ],
       [33. ]])

In [105]:
# impute multivariado
from sklearn.experimental import enable_iterative_imputer # modulo ainda em experimento
from sklearn.impute import IterativeImputer
from sklearn.tree import DecisionTreeRegressor as estim

imp2 = IterativeImputer(estimator=estim(),max_iter=10) # usando arvore de regressao para encontrar dados faltantes
imp2.fit(arr)
imp2.transform(arr)

array([[10. ],
       [14.5],
       [ 5. ],
       [10. ],
       [33. ]])