### Naive Bayes

# Abordagem teorema de bayes<br>
probabilidade condicional ex<br>
Risco de credito dado pela Historia de credito<br>
Previsao de falhas<br>
diagnosticos

 nao travalha bem com atributos independentes<br>
ele sofre com classes nao contidas no modelo(sim,nao) se chega uma classe desconhecida ele seta como null

Probabilidade a priori: probabilidade um fato ter ocorrido ou nao: Balança quebrar ou nao<br>
probabilidade de quebrar P(a) = 25% e Probabilidade de nao ter quebrado 75% <br>
P(B|A)= probabilidade da balanca ter quebrado dada q ela quebrou 90% , probabilidade de falar q quebou e ele nao quebrou P(B|A^c) = 5%<br>
Probababilibade conjunta: apriori*condicional: 0.25*0.9 = 0.225 22.5% do fato q balanca quebre e se ache o problema,P(A complementar) =0.75*0.05 = 0.0375= 3.75% chance de diagnosticar errado<br>
Probabilidade A posteriori: balanca estar quebrada de fato estar quebrada: teorema de bayes


In [2]:
from sklearn.naive_bayes import GaussianNB
import pickle as pkl 
import numpy as np 
import os 

with open('credit.pkl','rb') as d:
    x_train,y_train,x_test,y_test = pkl.load(d)

In [3]:
nv = GaussianNB()
nv.fit(x_train,y_train)

GaussianNB()

In [5]:
pred = nv.predict(x_test)

In [67]:
from sklearn.metrics import classification_report,accuracy_score,roc_auc_score

print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.97       436
           1       0.84      0.64      0.73        64

    accuracy                           0.94       500
   macro avg       0.89      0.81      0.85       500
weighted avg       0.93      0.94      0.93       500



In [68]:
roc_auc_score(y_test,pred)

0.8111381880733944

In [57]:
# unindo X e Y
x= np.r_[x_train,x_test]
y =np.r_[y_train,y_test]


2000

In [59]:
from sklearn.model_selection import KFold,cross_val_score

kfold = KFold(n_splits=30,shuffle=True,random_state=5)
np.mean(cross_val_score(GaussianNB(),x,y,cv=kfold))

0.9264736921453341

In [66]:
nv.classes_

array([0, 1], dtype=int64)

In [64]:
nv.class_count_ # quantidade de elementos na base 

array([1281.,  219.])

In [60]:
nv.class_prior_ # classes ele mostra a proporcao

array([0.854, 0.146])

In [71]:
nv.priors