# Calculando tamanho da amostra

#### Definindo o tamanho da amostra com a formula
N  -> Tamanho da populacao <br>
n  -> Tamanho da Amostra   <br>
n0 -> Primeira aproximação <br>
E0  -> Erro amostral toleravel :diferença entre valor verdadeiro e o valor do parametro a estimar <br>


In [118]:
N=2000 # populacao
n=300  # amostra
erro = 5/100 # 5% 
erro

0.05

In [ ]:
# Formula n0, se o valor for 20x igual a tamanho da populacao podemos utiliza-lo
# n0 = 1/E^2
###################
# 5% erro

n0 = round(1/ (erro**2))
n0

400

In [ ]:
# Formula fator de correcao  n
# n = N*n0/N+n0
n = round((N*n0)/(N+n0))
n

333

In [ ]:
def tam_amostra(N):
    n0 = round(1/ (erro**2))
    n0
    nn =n0*20
    if nn ==N :
        return n0
    else: 
        return round((N*n0)/(N+n0)) # fator de correcao



In [ ]:
tam_amostra(7999)

381

In [1]:
import numpy as np 

Gerando vetor normalizado<br>
 media, dvp e shape

In [3]:
vet =  np.random.normal(10,2,(100,1))
vet[:4]

array([[10.10831724],
       [11.43882345],
       [11.12762145],
       [11.27711305]])

<font color='yellow'><h2>Amostra Simples </h2></font>


In [11]:
# elementos a serem escolhidos, size, reposicao e probabilidade de cair o elemento
sel = np.random.choice([0,1],size=100,replace=True,p=[0.5,0.5])
sel

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0])

In [35]:
# porpocao da amostra
list(sel.ravel()).count(1)/len(vet) *100


48.0

In [38]:
v_amst = vet[sel==True]
v_amst[:4]

array([[11.43882345],
       [11.27711305],
       [ 9.22885098],
       [ 8.58534666]])

<font color='yellow'><h2>Amostra Sistematica </h2></font>


Quando temos um esquema, para escolher os dados<br><br>
<b> K =Intervalo de amostragem<br>
<b> N = total de individuos na populacao<br>
<b> n = total de ubdividuos da amostra

In [43]:
N = 30000          # Tamanho da populacao
n = 6000          # tamanho da amostra
k = np.random.choice(n,1)
k

array([1935])

In [48]:
1935/3.10077519

624.037500764446

In [67]:
menor = 0 
maior = 6000 
n_student = 30  # no minimo uma tsutdent 
dvp = 1.7733888345360762 # desvio padrao
inter = maior-menor # intervalo
k = inter/n_student # amplitude 
k = k/dvp # distancia dos pontos tem de corresponder ao desvio da media, usa-se para manter os intervalos em escalas padronizadas
k = round(k)
k

113

In [71]:
sistematica = np.arange(0,n,k)
sistematica

array([   0,  113,  226,  339,  452,  565,  678,  791,  904, 1017, 1130,
       1243, 1356, 1469, 1582, 1695, 1808, 1921, 2034, 2147, 2260, 2373,
       2486, 2599, 2712, 2825, 2938, 3051, 3164, 3277, 3390, 3503, 3616,
       3729, 3842, 3955, 4068, 4181, 4294, 4407, 4520, 4633, 4746, 4859,
       4972, 5085, 5198, 5311, 5424, 5537, 5650, 5763, 5876, 5989])

In [78]:
np.std(sistematica[40:50])

324.5677895293986

In [80]:
np.std(sistematica[30:40])

324.5677895293986

<font color='yellow'><h2>Amostra Estratificada </h2></font>

In [81]:
from sklearn.datasets import load_iris

iris = load_iris()
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [85]:
from sklearn.model_selection import train_test_split

display(list(iris.target).count(0),
        list(iris.target).count(1),
        list(iris.target).count(2))

50

50

50