Algebra linear e o campo da matematica que trabalha com equacoes lineares, representados em matrizes e vetores

indispensavel na modelagens de problemas matematicos

sistemas linear: e conjunto de equacoes lineares que possui equacoes n iconigtas e assum forma generica

$a00z0+a01x1...a01xn =y0$<br>
a:matriz, x:vetor<br>
apenas uma solucao por linha

matrix de coeficiente a * matriz de vetores = matriz de respostas

matriz m por n = m por 1

matriz identidade: elemento neutro

In [46]:
import numpy as np 
import numba as n # roda paralelo o numpy
import math 
import pandas as pd 
import scipy as sc
import sympy


In [47]:
a = np.array([1,2,3,4,5,6])# meu elementos tambem serao listas 
a.reshape(-1,2) # redimensionando 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
m1=np.array([[1,2,3],
         [4,5,6],
         [7,8,9]]) # lista bidimensional = matriz 
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

matriz quadrada: 2x2,3x3,4x4

Operacoes basicas com matriz

In [49]:
m2=m1*3
m2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [50]:
#Soma 
# soma e subtracao, pegar o mesmo elemento de cada matriz
# soma e subtracao devem ser de coisas de msm natureza 

c = m1+m2
c


array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [51]:
# multiplicao(matriz,escalar), escalar:numero 
k=10000 # meu escalar, quem sera o numero q vai multiplicar toda a matriz
c*k

array([[ 40000,  80000, 120000],
       [160000, 200000, 240000],
       [280000, 320000, 360000]])

In [52]:
k=2j  # pode ser um numero complexo
c*k

array([[0. +8.j, 0.+16.j, 0.+24.j],
       [0.+32.j, 0.+40.j, 0.+48.j],
       [0.+56.j, 0.+64.j, 0.+72.j]])

In [53]:
a=a.reshape(-1,2)
a,m2

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]]))

In [54]:
# multiplicacao de matrizes nao precisa ter coisas de msm natureza

# se as matrizes forem diferentes regra geral de matrizes 
# combinacao linear dos elementos da matriz
# multiplicar linha da matriz 1 pela coluna da matriz 2, asim obteremos x0,x1,x2 


a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

np.dot(a, b)


array([[4, 1],
       [2, 2]])

In [55]:
print(a)
print()
print(b)

[[1 0]
 [0 1]]

[[4 1]
 [2 2]]


In [56]:
# matriz especiais 
# indentidade, diagonal e 1 

np.eye(10) # usamos para tangir determinantes

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [57]:
#  matrizes 0  e 1 

np.zeros((2,2)),np.ones((2,2))

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.]]))

In [58]:
# matriz transposta 
# pivot
print(m1) 
print()
np.transpose(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [59]:
m1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [60]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
# matriz inversa
# 
# inverso dos valores  

np.invert(m1)

array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]], dtype=int32)

In [62]:
# solucao 
# inversao da matriz


In [63]:
# empilhando a matriz
# em vertical, coloca uma emcima da outra 
np.vstack([m1,m2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [65]:
# empilhando a matriz
# em horizontal, coloca uma do lado da outra 
np.hstack([m1,m2])

array([[ 1,  2,  3,  3,  6,  9],
       [ 4,  5,  6, 12, 15, 18],
       [ 7,  8,  9, 21, 24, 27]])

In [70]:
np.concatenate(([1,2,3],[4,5,6]))

array([1, 2, 3, 4, 5, 6])