Notacao Aij(linha,coluna)<br>
$$\begin{bmatrix} 1 & 2  \\ 0 & 2  \end{bmatrix}$$

Matriz linha(vetor linha) <br>
$$\begin{bmatrix} 1 & 2  \end{bmatrix}$$

Matriz coluna(vetor coluna) <br>
$$\begin{bmatrix} 1 \\ 2 \\  3 \end{bmatrix}$$

Matriz transposta: pivot (matriz 3x2 vira 2x3)<br>
$$\begin{bmatrix} 1 & 3 \\ 2 & 5  \\  3 & 4 \end{bmatrix}$$
$$\begin{bmatrix} 1 & 2 & 3  \\ 3 & 5 & 4  \end{bmatrix}$$

In [1]:
import numpy as np 

matriz = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]]) # melhor usar, array, pois a funcao matrix sera depreciada
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
np.diag((2,4,6,8,10)) # matris diagonal

array([[ 2,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0, 10]])

In [3]:
# tranpos matriz, linha vira coluna e vice versa
matriz.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
# matriz linha
np.array([[2,4,5]])

array([[2, 4, 5]])

In [5]:
np.array([[2],[4],[5]]) #matriz coluna

array([[2],
       [4],
       [5]])

In [39]:
from sympy import * 

m = Matrix(3,2,[2,4,7,5,8,30]) # 3 colunas x 2 linhas
m

Matrix([
[2,  4],
[7,  5],
[8, 30]])

In [28]:
m[1,[0,1]]

Matrix([[5, 8]])

####  multiplicacao entr matrizes devem ser, numero de linhas deve ser o mesmo do numero de colunas


In [47]:
m.shape,m2.shape

((3, 2), (2, 3))

In [38]:
m2 = Matrix(2,3,[2,4,3,5,8,6])# 2 linhas X 3 colunas
m2

Matrix([
[2, 4, 3],
[5, 8, 6]])

In [42]:
m*m2 # multiplica elemento da linha da primeira matriza pela coluna da segunda

Matrix([
[ 24,  40,  30],
[ 39,  68,  51],
[166, 272, 204]])

In [45]:
m2*m # ordem importa

Matrix([
[ 56, 118],
[114, 240]])

In [56]:
# linhas e colunas iguais podemos multiplicar
m.shape[0],m2.shape[1]

(3, 3)

In [55]:
# numero de colunas tem q ser igual numero de linhas
m = np.array(m).astype(np.float64) 
m2 = np.array(m2).astype(np.float64)
np.dot(m,m2)

array([[ 24.,  40.,  30.],
       [ 39.,  68.,  51.],
       [166., 272., 204.]])

### Determinante

matriz 2 x 2:produto da diagonal principal - produto da diagonal secundaria, quando temos um determante temos solucao para o sistema<br>
matriz 3 x 3: regra de sarri(sarrus): repete as duas primeiras coluna sno final e multiplica as diagonais a direita soma, as diagonais a esquerda multiplica e subtrai, soma todos os valores<br>
apenas determinante =0 nao tem solucao


qualquer ordem de matriz, usamo o <b>Teorema de Laplace</b>
1.cofator <br>
D= Soma Aij*Cij


In [62]:
# nao resulta em uma matriz identidade, entao uma nao e uma matriz inversa
np.dot(m,m2)

array([[ 24.,  40.,  30.],
       [ 39.,  68.,  51.],
       [166., 272., 204.]])

In [66]:
# matriz inversa, onde obtemos como resultado uma matriz identidade 
m5 = np.array([[2,5],
               [1,3 ]])

m6 = np.array([[3,-5],
               [-1,2 ]])
np.dot(m5,m6)

array([[1, 0],
       [0, 1]])

In [67]:
# nem toda matriz tem uma inversa, entao quando nao tiver ira dar erro
np.linalg.inv(m5)

array([[ 3., -5.],
       [-1.,  2.]])

#### Determinante

In [88]:
mm = Matrix(4,4,[1,3,2,4,6,5,7,9,10,12,11,13,15,14,16,17])# lei de formacao qualquer 
mm

Matrix([
[ 1,  3,  2,  4],
[ 6,  5,  7,  9],
[10, 12, 11, 13],
[15, 14, 16, 17]])

In [89]:
mx=np.array(mm).astype(np.float64)
mx

array([[ 1.,  3.,  2.,  4.],
       [ 6.,  5.,  7.,  9.],
       [10., 12., 11., 13.],
       [15., 14., 16., 17.]])

In [90]:
np.linalg.det(mx)

-26.99999999999998

In [93]:
import scipy as sp 
from scipy import linalg

sp.linalg.det(mx) # melhor usar aqui o determinante

-27.000000000000007

In [103]:
t = np.array([[0,2],[0,-6]])
sp.linalg.det(t) # nao tem uma matriz inversa

0.0