Sistemas de equacoes lineares: sao quando temos varias equacoes juntas e precisamos encontrar os valores de suas iconigtas<br>


$$2x+4x+z+2w=2$$
$$3x_0-3x_1-x_2-x_3=2$$


<img src="tipos.png" alt="Italian Trulli">


# Regra de cramer

Matriz dos coeficients * Vetor das incogntas = constantes

In [25]:
# 1 pessoa A e 4 produtos B =200
# 2 pessoa 2A e 3 B por 180 
# qual valor do A e B

from sympy import * 
import numpy as np 

# 1A +4B=200
# 2A+3B=180
#Matriz dos coeficientes
x = np.array([[1,4],[2,3]]) # Primeira icongnta, segunda icnita de forma linear
# Matriz coluna das constantes
y=np.array([200,180])# CONSTANTES
np.linalg.solve(x,y)# valor de A e valor de B
#b=44
#a=24

array([24., 44.])

$$1A+4B=200$$ 
$$2A+3B=180$$

$\begin{bmatrix} 1 & 4 \\ 2 & 3 \end{bmatrix}$ $*\begin{pmatrix} A_1 & B_1  \end{pmatrix}$  $=\begin{pmatrix} 200 & 180 \end{pmatrix}$


In [27]:
import scipy as s 

A= s.linalg.det(np.array([[1,4],[2,3]])) # determinante da matriz , regra sarrus
# determinante de cada iconigta, sera substituir na matriz original os valores das contates de acordo com a possicao das iconigtas no vetor 
# mtt complexo para fazer na mao 
A 

-5.0

Metodo eliminacao de Guass (escalonamento)

Subdeterminado: mais iconigtas que equações<br>
SuperDeterminado: Mais equações do que iconigtas<br>
ambosnao tem solução exata

<img src="tipos_problemas.png" alt="Italian Trulli">


In [5]:
# para esse problemas usamos minimos quadrados

In [14]:
import numpy as np 
import pandas as pd
import scipy 

# meses estudados
# tempo por dia
# nota 

x = np.random.randint(5,20,50) #meses de estuso 
x2 = np.random.randint(5,150,50) #tempo de estudo por dia 
y = np.random.randint(1,10,50) #nota


In [15]:
d = {'meses':x,
     'tempo_dia':x2,
     'nota':y}

dd=pd.DataFrame(d)
dd.head()

meses  tempo_dia  nota
0     10         82     8
1     12         48     3
2     10         91     3
3     16        123     3
4      9         18     2

In [16]:
dd.shape

(50, 3)

In [20]:
# matriz de iconigtas 
a = dd.iloc[:,0:2].values

In [21]:
# matriz de constatntes
b = dd.iloc[:,2].values
b

array([8, 3, 3, 3, 2, 9, 2, 6, 2, 8, 8, 4, 7, 2, 4, 4, 8, 3, 2, 2, 2, 4,
       8, 9, 2, 2, 6, 9, 3, 7, 1, 3, 8, 2, 4, 6, 7, 1, 6, 6, 1, 2, 8, 5,
       9, 2, 2, 5, 7, 6])

In [23]:
# pegando a matriz transposta
a_t = np.array(a).T
a_t

array([[ 10,  12,  10,  16,   9,   5,  19,  14,   7,  19,   7,  14,  18,
         19,  13,   5,  13,  10,  16,   9,   5,   9,  16,  15,  14,  14,
          8,  18,   6,  19,   5,   6,   6,   5,   7,  11,   8,   7,  16,
         14,   7,  11,  14,   6,   7,   6,   5,  10,  16,  18],
       [ 82,  48,  91, 123,  18,  80,  23,  86, 127,  58, 109,  87,  23,
         22,  90, 136,  56, 143,  49,  59,  92,  63,  29, 117,  47,  44,
        106,  48, 124,  12,  42, 141,  46, 107, 110, 117, 139,  96,  15,
         96, 100,  91,  94, 101,  79, 136,  24,  80,  96,  39]])

In [25]:
atxa = np.dot(a_t,a) # nao gerou uma matriz indentidade
atxa

array([[  7216,  39250],
       [ 39250, 382019]])

In [27]:
a_inv = np.linalg.inv(atxa)
a_inv

array([[ 3.14137989e-04, -3.22756618e-05],
       [-3.22756618e-05,  5.93378792e-06]])

In [29]:
atb = np.dot(a_t,b)
atb

array([ 2747, 18127])

In [31]:
x=np.dot(a_inv,atb)
x # x e y , melhor ajuste, minimo da funcao

array([0.27787613, 0.01890053])

In [47]:
np.dot(np.array([5,12]),x)

1.616187031857149

In [56]:
dd.iloc[:,:].sort_values(by='nota',ascending=False)

meses  tempo_dia  nota
23     15        117     9
44      7         79     9
27     18         48     9
5       5         80     9
22     16         29     8
16     13         56     8
32      6         46     8
10      7        109     8
0      10         82     8
42     14         94     8
9      19         58     8
36      8        139     7
12     18         23     7
29     19         12     7
48     16         96     7
38     16         15     6
35     11        117     6
39     14         96     6
26      8        106     6
49     18         39     6
7      14         86     6
47     10         80     5
43      6        101     5
15      5        136     4
21      9         63     4
34      7        110     4
11     14         87     4
14     13         90     4
17     10        143     3
28      6        124     3
31      6        141     3
3      16        123     3
1      12         48     3
2      10         91     3
6      19         23     2
45      6        136     2
46      5         24     2
4       9         18     2
41     11         91     2
20      5         92     2
8       7        127     2
33      5        107     2
13     19         22     2
24     14         47     2
18     16         49     2
19      9         59     2
25     14         44     2
40      7        100     1
37      7         96     1
30      5         42     1

In [57]:

from sklearn.metrics import mean_absolute_error
dd['prev'] = np.dot(a,x)
mean_absolute_error(dd['nota'] ,dd['prev'] ) # algotitimo erra muito 


2.076411478569334

In [58]:
dd['arr_abs']= abs(dd['nota'] -dd['prev'] )
dd['arr_abs']

0     3.671395
1     1.241739
2     1.498710
3     3.770783
4     0.841095
5     6.098577
6     3.714359
7     0.484289
8     2.345500
9     1.624123
10    3.994709
11    1.534612
12    1.563517
13    3.695458
14    1.313437
15    0.040147
16    3.329181
17    2.481537
18    3.372144
19    1.616016
20    1.128229
21    0.308381
22    3.005866
23    2.620496
24    2.778591
25    2.721889
26    1.773535
27    3.091004
28    1.010923
29    1.493547
30    1.183203
31    1.332232
32    5.463319
33    1.411737
34    0.024191
35    0.732000
36    2.149817
37    2.759584
38    1.270474
39    0.295283
40    2.835186
41    2.776586
42    2.333084
43    1.423790
44    5.561725
45    2.237729
46    0.157007
47    0.709196
48    0.739531
49    0.261109
Name: arr_abs, dtype: float64

In [59]:
dd['arr_abs'].mean()

2.076411478569334

In [ ]:
# se aparecer um zero, sofre perca de sentido nas informacoes, por isso utilizamos regressao linear multipla