T(x,y) =  4x+5y , 2x+y<br>
T(5,2) 4*5+5*2, 2*5+2<br>
t(5,2) =(30,12), colocando em evidencia <br>
 6.(5,2) ou seja o meu 6 e o auto valor e o meu 5,2 autovetor 


In [4]:
6*(5),6*2 

(30, 12)

In [5]:
import numpy as np

A = np.array([[3,0],
              [0,1]])
A

array([[3, 0],
       [0, 1]])

In [8]:
AUTOVALOR, AUTOVETOR = np.linalg.eig(A)
AUTOVETOR

array([[1., 0.],
       [0., 1.]])

In [9]:
AUTOVALOR # X 1 =3,x 0 =1

array([3., 1.])

In [13]:
b = np.array([[4,-5],
              [66,1]])

In [14]:
av , avet = np.linalg.eig(b)

In [15]:
av

array([2.5+18.10386699j, 2.5-18.10386699j])

In [16]:
avet

array([[0.02191241+0.26446622j, 0.02191241-0.26446622j],
       [0.96414598+0.j        , 0.96414598-0.j        ]])

### PCA

TECNICA QUE TRANSFORMA UM CONJUNTO DE VARIAVIES ORIGINAIS EM UM POUTRO CONJUNTO DE VARIVEIS, SEM CRORRELACAO QUE EXPLICAM MELHOR A VARIANCIA DOS DADOS

DETERMINADO PELOS AUTOVETORES DA MATRIZ DE COVARIANCIA