Subamostragem:undersampling<br>
Sobamostragem:Oversampling

subamostragem: seleciona da classe com maior numero de registros e diminuimos, perde-se informacoes<br>
Sobamostragem: copias(registros similares) da classe menor para deixar ela com mesmo tamanho da maior classe

<font color='yellow'><h2>Algoritimos de subamsotragem </h2></font>

Tomek Links: criar uma separacao entre as classes excluindo os valores que se aproximam muito de uma classe a outra, criando uma superfice para nao atrapalhar classificacao

In [4]:
# conda install -c conda-forge imbalanced-learn

In [5]:
from imblearn.under_sampling import TomekLinks
import sklearn.datasets as dt 
import numpy as np

db =dt.load_wine()


In [6]:
# ira apagar registro somente da classe majoritaria

y = db.target 
x = db.data 

tl = TomekLinks(sampling_strategy='majority')
X_under, y_under = tl.fit_sample(db.data, db.target)


In [7]:
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([59, 71, 48], dtype=int64))

In [8]:
np.unique(y_under,return_counts=True)

(array([0, 1, 2]), array([59, 62, 48], dtype=int64))

<font color='yellow'><h2>Algoritimos de Sobamsotragem </h2></font>

SMOTE

calcula a distancia dos dados faltantes e cria dados para aumentar o tamanho da classe de modo que ela fique com mesma quantidade da classe maior

In [9]:
from imblearn.over_sampling import SMOTE

In [10]:
smote = SMOTE(sampling_strategy='minority')
X_over, y_over = smote.fit_sample(db.data, db.target)

In [11]:
np.unique(y, return_counts=True)

(array([0, 1, 2]), array([59, 71, 48], dtype=int64))

In [12]:
np.unique(y_over, return_counts=True)

(array([0, 1, 2]), array([59, 71, 71], dtype=int64))