Teste para indentificar se as proporcoes das variaeis qualitativas sao diferentes ou seja existe tendencia(amostras indenpendestes)<br>
tambem usado para testar se variaveis de classificacao sao independentes 

Teste bivariado<br>
Teste Qui-Quadrado (Variáveis Qualitativas)<br>
Correlação de Pearson (Variáveis Quantitativas)

h0: independentes <br>
h1: dependentes

In [17]:
from scipy.stats import chi2_contingency 

_,p,_,_=chi2_contingency(d) # _,p, frequencia esperada 
if p<= 0.05:
    print('Hipotese nula rejeita') # nao existe diferenca significativa nesse conjunto de dados
else:
    print('Hipotese alternativa rejeitada')# existe diferenca, no conjunto ou seja uma tendencia

Hipotese alternativa rejeitada


#### selecao dos melhores atributos

In [18]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import SelectFdr,chi2
from sklearn.metrics import accuracy_score 

iris = load_iris()

In [19]:
x = iris.data
y=iris.target

In [20]:
sel = SelectFdr(chi2,alpha=0.01)
x_nv = sel.fit_transform(x,y)
sel.pvalues_

array([4.47651499e-03, 1.56395980e-01, 5.53397228e-26, 2.75824965e-15])

In [21]:
# os true indica diferenca estatistica,negando h0
sel.pvalues_ <=0.01

array([ True, False,  True,  True])

In [22]:
import numpy as np

col = sel.get_support()# mostra colunas selecionadas 
np.where(col==True) # retorno o indice das colunas selecionadas 


(array([0, 2, 3], dtype=int64),)

In [ ]:
# fdr, usado para controlar erro do tipo i